Repository artursanntos/vfoods-backend, pull requests merged in 2023-10, with the labels that each got.

#17 feat: metodo getIndicatorById
  src/modules/indicador/indicador.controller.ts
  src/modules/indicador/indicador.service.ts
Labels: enhancement, hacktoberfest-accepted

#20 Estruturação do README
  README.md
Labels: documentation, hacktoberfest-accepted

#19 Adicionando função para o gráfico de perfil do colaborador
  src/modules/colaborador-indicador/colaborador-indicador.controller.ts
  src/modules/colaborador-indicador/colaborador-indicador.service.ts
Labels: hacktoberfest-accepted

#23 feature: get indicadores em colaboradoresIndicadores
  src/modules/colaborador-indicador/colaborador-indicador.controller.ts
  src/modules/colaborador-indicador/colaborador-indicador.service.ts
Labels: enhancement, hacktoberfest-accepted

#24 Adicionando intervalo modificavel a função aux do gráfico do colab
  src/modules/colaborador-indicador/colaborador-indicador.controller.ts
  src/modules/colaborador-indicador/colaborador-indicador.service.ts
Labels: hacktoberfest-accepted

#26 feature: get colaboradoresIndicadores por mes do colaborador no indicador
  src/modules/colaborador-indicador/colaborador-indicador.controller.ts
  src/modules/colaborador-indicador/colaborador-indicador.service.ts
Labels: enhancement, hacktoberfest-accepted

#29 fix: CreateMany apenas com o mes da DeadLine Colab.-Ind.
  src/modules/colaborador-indicador/colaborador-indicador.service.ts
Labels: hacktoberfest-accepted

#31 bug: adiconou ==
  src/modules/colaborador-indicador/colaborador-indicador.service.ts
Labels: bug, hacktoberfest-accepted
